sudo: true
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

env:
  - DB=mysql

before_script:
  - mysql -e "create database IF NOT EXISTS hackademic;" -uroot
  - mysql -uroot "hackademic" < "installation/sql/db.sql"

script:
  - vendor/bin/phpunit --configuration phpunit_mysql.xml --coverage-html ./report hackademic_devtests/successTest.php

install:
 - composer install

notifications:
  irc:
    channels: "irc.freenode.org#hackademic-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false

after_success:
  coveralls --rcfile=.coveragerc
