---
- name: MySQL
  apt: pkg=mysql-server state=installed

- name: MySQL
  apt: pkg=python-mysqldb state=installed

- name: MySQL | Set Password
  mysql_user: name={{ db_user }} host={{ item }} password={{ db_pass }} priv=*.*:ALL,GRANT
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: MySQL | Copy Config File
  template: src=../files/mysql/.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: MySQL | Create App DB
  mysql_db: name={{ db_name }} state=present login_password={{ db_pass }} login_user={{ db_user }}